<a href="https://colab.research.google.com/github/Silverstrive/Naufaliawan-Ghibran/blob/main/Kelompok_7_Tugas_M5_PSD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TUGAS
## Pengenalan Array dengan Numpy

Kelompok 7

1. Ikhwan Maulana

2. Micoandar Justinus Marbun

3. Naufaliawan Ghibran

4. Raka Abdilah

5. Reizza Aliffian



In [1]:
# import libraries
import numpy as np

# buat matriks (arr) shape 2x3 dengan tipe data integer 64
arr = np.array([[1, 2, 3], [5, 6, 7]], dtype=np.int64)

# print arr
print("Array:")
print(arr)

# print shape arr
print("\n Shape Array:")
print(arr.shape)

# print tipe data arr
print("\nTipe Data Array:")
print(arr.dtype)

Array:
[[1 2 3]
 [5 6 7]]

 Shape Array:
(2, 3)

Tipe Data Array:
int64


In [2]:
import numpy as np

# buat matriks (arr_rdm) shape 2x3 dengan tipe data integer 64
# nilai elemennya random
arr_rdm = np.random.randint(0, 100, size=(2, 3), dtype=np.int64)

# print arr_rdm
print("Array Random:")
print(arr_rdm)

# print shape arr_rdm
print("\nShape Array Random:")
print(arr_rdm.shape)

# print tipe data arr_rdm
print("\nTipe Data Array Random:")
print(arr_rdm.dtype)

Array Random:
[[20 55 20]
 [52 23 26]]

Shape Array Random:
(2, 3)

Tipe Data Array Random:
int64


# Aritmatika Dasar dengan Numpy

In [11]:
arr = np.array([[1, 2, 3], [5, 6, 7]], dtype=np.int64)
arr_rdm = np.random.randint(0, 100, size=(2, 3), dtype=np.int64)
print(arr)
print(arr_rdm)
# operasi penjumlahan arr dan arr_rdm
sum_arr = np.add(arr, arr_rdm)
print("\nHasil penjumlahan arr dan arr_rdm:")
print(sum_arr)

# operasi pengurangan arr dan arr_rdm
sub_arr = np.subtract(arr, arr_rdm)
print("\nHasil pengurangan arr dan arr_rdm:")
print(sub_arr)

# operasi perpangkatan dua arr_rdm
pow_arr_rdm = np.power(arr_rdm, 2)
print("\nHasil perpangkatan dua arr_rdm:")
print(pow_arr_rdm)

# operasi perkalian elemen arr dan arr_rdm
mul_arr = np.multiply(arr, arr_rdm)
print("\nHasil perkalian elemen arr dan arr_rdm:")
print(mul_arr)

# Transpose matriks arr_rdm
transp_arr_rdm = arr_rdm.T
print("\nTranspose matriks arr_rdm:")
print(transp_arr_rdm)

# operasi perkalian matriks arr dan arr_rdm
transp_mul_arr = np.dot(arr, arr_rdm.T)
print("\nOperasi perkalian matriks arr dan transp_arr_rdm ")
print(transp_mul_arr)

[[1 2 3]
 [5 6 7]]
[[58 18 88]
 [33 98 42]]

Hasil penjumlahan arr dan arr_rdm:
[[ 59  20  91]
 [ 38 104  49]]

Hasil pengurangan arr dan arr_rdm:
[[-57 -16 -85]
 [-28 -92 -35]]

Hasil perpangkatan dua arr_rdm:
[[3364  324 7744]
 [1089 9604 1764]]

Hasil perkalian elemen arr dan arr_rdm:
[[ 58  36 264]
 [165 588 294]]

Transpose matriks arr_rdm:
[[58 33]
 [18 98]
 [88 42]]

Operasi perkalian matriks arr dan transp_arr_rdm 
[[ 358  355]
 [1014 1047]]


In [13]:
arr = np.array([[1, 2, 3], [5, 6, 7]], dtype=np.int64)

# print nilai rata-rata arr
mean_arr = np.mean(arr)
print("Nilai rata-rata arr")
print(mean_arr)

# print nilai rata-rata per baris arr
mean_row_arr = np.mean(arr, axis=1)
print("\nNilai rata-rata per baris matriks arr:")
print(mean_row_arr)

# print total nilai seluruh elemen matriks arr
sum_total_arr = np.sum(arr)
print("\nTotal nilai seluruh elemen matriks arr:")
print(sum_total_arr)

# print nilai maximal per kolom matriks arr
max_col_arr = np.max(arr, axis=0)
print("\nNilai maksimal per kolom matriks arr:")
print(max_col_arr)

Nilai rata-rata arr
4.0

Nilai rata-rata per baris matriks arr:
[2. 6.]

Total nilai seluruh elemen matriks arr:
24

Nilai maksimal per kolom matriks arr:
[5 6 7]


# Fitur pada Numpy

In [3]:
# buat array arrg dengan nilai range 1-20
arrg = np.arange(1, 21)


# print arrg
print("Array arrg:")
print(arrg)

# print nilai arrg index 5
print("\nNilai arrg index 5:")
print(arrg[5])

# print nilai arrg untuk 3 elemen dari terakhir
print("\nNilai arrg untuk 3 elemen dari terakhir:")
print(arrg[-3:])

# print nilai arrg 3 sampai 6
print("\nNilai arrg 3 sampai 6:")
print(arrg[2:6])

Array arrg:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Nilai arrg index 5:
6

Nilai arrg untuk 3 elemen dari terakhir:
[18 19 20]

Nilai arrg 3 sampai 6:
[3 4 5 6]


In [6]:
# print matriks arr
arr = np.array([[1, 2, 3], [5, 6, 7]], dtype=np.int64)
print("Matriks arr:")
print(arr)


# print slice matriks arr dengan output
## [[ 2  3 ]
##  [ 6  7 ]]
print("\nSlice matriks arr [[2, 3], [6, 7]]:")
print(arr[:, 1:])

# print slice matriks arr dengan output
## [[ 3 ]
##  [ 7 ]]
print("\nSlice matriks arr [[3], [7]]:")
print(arr[:, 2:])


Matriks arr:
[[1 2 3]
 [5 6 7]]

Slice matriks arr [[2, 3], [6, 7]]:
[[2 3]
 [6 7]]

Slice matriks arr [[3], [7]]:
[[3]
 [7]]


In [10]:
# buat matriks mtx_rdm ukuran 3x4 dengan tipe data integer, isi elemennya random
mtx_rdm = np.random.randint(0, 100, size=(3, 4), dtype=np.int64)
# print mtx_rdm shape
print("Bentuk mtx_rdm sebelum perubahan:", mtx_rdm.shape)
# ubah shape mtx_rdm menjadi satu dimensi
mtx_rdm_1d = mtx_rdm.flatten()
print("\nBentuk mtx_rdm menjadi satu dimensi:")
print(mtx_rdm_1d.shape)
print("\n", mtx_rdm_1d)
# ubah shape mtx_rdm menjadi 6x2
mtx_rdm_6x2 = mtx_rdm.reshape(6, 2)
print("\nBentuk mtx_rdm menjadi 6x2:")
print(mtx_rdm_6x2.shape)
print("\n", mtx_rdm_6x2)

Bentuk mtx_rdm sebelum perubahan: (3, 4)

Bentuk mtx_rdm menjadi satu dimensi:
(12,)

 [32 15 70  5 81 70 22  3 69 77 99 21]

Bentuk mtx_rdm menjadi 6x2:
(6, 2)

 [[32 15]
 [70  5]
 [81 70]
 [22  3]
 [69 77]
 [99 21]]
